import { FormEvent, useEffect, useState } from "react";
import { api, post, put } from "./api";
import { Button, Chip, ErrorState, LoadingState, titleCase } from "./components";
import type { JsonRecord } from "./types";

const sections = ["models", "telegram", "security", "privacy"] as const;
type Section = typeof sections[number];

export function SetupDrawer({ open, onClose }: { open: boolean; onClose: () => void }) {
  const [active, setActive] = useState<Section>("models");
  const [status, setStatus] = useState<JsonRecord | null>(null);
  const [form, setForm] = useState<Record<string,string>>({});
  const [attempt, setAttempt] = useState("");
  const [loginState, setLoginState] = useState("");
  const [error, setError] = useState("");
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);

  async function refresh() {
    try {
      setError("");
      const [nextStatus, models, retention] = await Promise.all([api<JsonRecord>("/api/setup/status"), api<JsonRecord>("/api/models/status"), api<JsonRecord>("/api/retention")]);
      setStatus(nextStatus);
      const modelMap = (models.models || {}) as JsonRecord;
      const policy = (retention.policy || {}) as JsonRecord;
      const paths = (nextStatus.paths || {}) as JsonRecord;
      setForm(previous => ({...previous,HIVE_LLM_BASE_URL:String(models.endpoint || ""),HIVE_LLM_MODEL_CHEAP:String(modelMap.cheap || ""),HIVE_LLM_MODEL_STRONG:String(modelMap.strong || ""),HIVE_LLM_MODEL_LIGHT:String(modelMap.light || ""),HIVE_VISION_MODEL:String(modelMap.vision || ""),session_path:String(paths.session || "./secrets/user.session"),signing_path:String(paths.signing_key || "./secrets/signing_key.pem"),media_days:String(policy.media_days || 30),demo_days:String(policy.demo_days || 90),evaluation_days:String(policy.evaluation_days || 180),active_checkpoint_review_days:String(policy.active_checkpoint_review_days || 7)}));
    } catch (reason) { setError(message(reason)); }
  }
  useEffect(() => { if (open) void refresh(); }, [open]);
  useEffect(() => { if (!open) return; const handler = (event:KeyboardEvent) => { if(event.key === "Escape") onClose(); }; window.addEventListener("keydown",handler); return () => window.removeEventListener("keydown",handler); }, [open,onClose]);
  if (!open) return null;
  const checks=(status?.checks || {}) as Record<string,boolean>;
  const readyCount=Object.values(checks).filter(Boolean).length;
  const total=Object.keys(checks).length;
  async function run(task:()=>Promise<void>){setBusy(true);setError("");setNotice("");try{await task();}catch(reason){setError(message(reason));}finally{setBusy(false);}}
  async function saveModels(event:FormEvent){event.preventDefault();await run(async()=>{const payload=Object.fromEntries(Object.entries(form).filter(([key,value])=>key.startsWith("HIVE_")&&value.trim()));await put("/api/setup/config",payload);setNotice("Model routing saved. Restart the agent to apply it.");});}
  async function probeModels(){await run(async()=>{const result=await post<JsonRecord>("/api/models/probe");setNotice(String(result.detail || "Model endpoint check passed."));});}
  async function verifyBot(event:FormEvent){event.preventDefault();await run(async()=>{const result=await post<JsonRecord>("/api/setup/bot/verify",{token:form.bot_token||"",operator_id:form.operator_id||"",operator_name:form.operator_name||""});const bot=(result.bot||{}) as JsonRecord;setNotice(`Control bot verified${bot.username?` as @${bot.username}`:""}.`);await refresh();});}
  async function startLogin(event:FormEvent){event.preventDefault();await run(async()=>{const result=await post<JsonRecord>("/api/setup/telethon/start",{api_id:Number(form.api_id||0),api_hash:form.api_hash||"",phone:form.phone||"",passphrase:form.passphrase||"",session_path:form.session_path||"./secrets/user.session"});setAttempt(String(result.attempt_id||""));setLoginState(String(result.state||"code_required"));setNotice("Telegram sent a login code to the account.");});}
  async function submitCode(event:FormEvent){event.preventDefault();await run(async()=>{const result=await post<JsonRecord>("/api/setup/telethon/code",{attempt_id:attempt,code:form.login_code||""});setLoginState(String(result.state||""));setNotice(result.state==="ready"?"Telegram data plane authorised.":"Two-step verification password required.");if(result.state==="ready")await refresh();});}
  async function submitPassword(event:FormEvent){event.preventDefault();await run(async()=>{await post("/api/setup/telethon/password",{attempt_id:attempt,password:form.tg_password||""});setLoginState("ready");setNotice("Telegram data plane authorised.");await refresh();});}
  async function createKey(){await run(async()=>{await post("/api/setup/signing-key",{path:form.signing_path||""});setNotice("Evidence signing key is ready.");await refresh();});}
  async function rotateKey(){const key=(status?.signing_key||{}) as JsonRecord;const fingerprint=String(key.fingerprint||"");if(!fingerprint||!window.confirm(`Rotate signing key ${fingerprint}? The previous key remains stored for verification.`))return;await run(async()=>{await post("/api/setup/signing-key/rotate",{confirm_fingerprint:fingerprint,reason:"operator initiated from setup drawer"});setNotice("Signing key rotated. Restart the agent before sealing new evidence.");await refresh();});}
  async function savePanelToken(event:FormEvent){event.preventDefault();await run(async()=>{if(!form.panel_token?.trim())throw new Error("Enter a replacement panel token.");await put("/api/setup/config",{HIVE_PANEL_TOKEN:form.panel_token.trim()});setNotice("Panel token saved. Refresh after the runtime reloads configuration.");});}
  async function saveRetention(event:FormEvent){event.preventDefault();await run(async()=>{await put("/api/retention/policy",{media_days:Number(form.media_days||30),demo_days:Number(form.demo_days||90),evaluation_days:Number(form.evaluation_days||180),active_checkpoint_review_days:Number(form.active_checkpoint_review_days||7)});setNotice("Retention policy saved. This report-only policy does not delete artifacts.");});}

  return <div className="drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><aside className="setup-drawer" role="dialog" aria-modal="true" aria-label="Setup"><header><div><p className="eyebrow">Readiness</p><h2>{total&&readyCount===total?"All checks passing":`${readyCount} of ${total||5} checks passing`}</h2><p>Setup only demands attention when a required check fails.</p></div><button className="icon-button" onClick={onClose} aria-label="Close setup">×</button></header><nav>{sections.map(section=><button key={section} className={active===section?"active":""} onClick={()=>setActive(section)}><span className={`status-dot ${sectionReady(section,checks)?"healthy":"warning"}`}/><span><strong>{titleCase(section)}</strong><small>{sectionCopy(section)}</small></span><Chip tone={sectionReady(section,checks)?"success":"warning"}>{sectionReady(section,checks)?"Ready":"Review"}</Chip></button>)}</nav><div className="drawer-content">{!status&&!error&&<LoadingState label="Checking setup"/>}{error&&<ErrorState message={error}/>} {notice&&<div className="inline-notice">{notice}</div>}
    {status&&active==="models"&&<form onSubmit={saveModels}><h3>Model routing</h3><p>Assign each task to the configured compatible model endpoint.</p><div className="form-grid"><Field label="API base URL" name="HIVE_LLM_BASE_URL" form={form} setForm={setForm}/><Field label="New API key (optional)" name="HIVE_LLM_API_KEY" type="password" form={form} setForm={setForm}/><Field label="Cheap model" name="HIVE_LLM_MODEL_CHEAP" form={form} setForm={setForm}/><Field label="Strong model" name="HIVE_LLM_MODEL_STRONG" form={form} setForm={setForm}/><Field label="Verdict model" name="HIVE_LLM_MODEL_LIGHT" form={form} setForm={setForm}/><Field label="Vision model" name="HIVE_VISION_MODEL" form={form} setForm={setForm}/></div><div className="button-stack"><Button tone="primary" disabled={busy} type="submit">Save model routing</Button><Button disabled={busy} onClick={()=>void probeModels()}>Test endpoint</Button></div></form>}
    {status&&active==="telegram"&&<div className="setup-stack"><form onSubmit={verifyBot}><h3>Control bot</h3><p>Verify the bot used for operator approvals and evidence delivery.</p><div className="form-grid"><Field label="Bot token" name="bot_token" type="password" form={form} setForm={setForm}/><Field label="Operator ID" name="operator_id" form={form} setForm={setForm}/><Field label="Operator name" name="operator_name" form={form} setForm={setForm}/></div><Button tone="primary" disabled={busy} type="submit">Verify control bot</Button></form><form onSubmit={startLogin}><h3>Telegram data plane</h3><p>Authorise the approved research account. The encryption passphrase has no recovery path.</p><div className="form-grid"><Field label="API ID" name="api_id" form={form} setForm={setForm}/><Field label="API hash" name="api_hash" type="password" form={form} setForm={setForm}/><Field label="Phone" name="phone" form={form} setForm={setForm}/><Field label="Encryption passphrase" name="passphrase" type="password" form={form} setForm={setForm}/><Field label="Session path" name="session_path" form={form} setForm={setForm}/></div><Button tone="primary" disabled={busy} type="submit">Send login code</Button></form>{attempt&&loginState!=="ready"&&<form onSubmit={loginState==="password_required"?submitPassword:submitCode}><h3>{loginState==="password_required"?"Two-step verification":"Login code"}</h3><Field label={loginState==="password_required"?"Telegram password":"Code"} name={loginState==="password_required"?"tg_password":"login_code"} type={loginState==="password_required"?"password":"text"} form={form} setForm={setForm}/><Button tone="primary" disabled={busy} type="submit">Continue</Button></form>}</div>}
    {status&&active==="security"&&<div className="setup-stack"><div><h3>Evidence signing</h3><p>Signing proves sealed bytes have not changed; it does not prove sender identity.</p><Field label="Signing key path" name="signing_path" form={form} setForm={setForm}/><div className="button-stack"><Button tone="primary" disabled={busy} onClick={()=>void createKey()}>Create or verify key</Button><Button tone="danger" disabled={busy||!Boolean((status.signing_key as JsonRecord)?.rotation_allowed)} onClick={()=>void rotateKey()}>Rotate key</Button></div></div><form onSubmit={savePanelToken}><h3>Panel access</h3><p>Changing this token invalidates the browser session after configuration reload.</p><Field label="Replacement panel token" name="panel_token" type="password" form={form} setForm={setForm}/><Button tone="primary" disabled={busy} type="submit">Save panel token</Button></form></div>}
    {status&&active==="privacy"&&<form onSubmit={saveRetention}><h3>Retention policy</h3><p>Choose review thresholds for locally held artifacts. Saving never deletes anything.</p><div className="form-grid"><Field label="Captured media days" name="media_days" type="number" form={form} setForm={setForm}/><Field label="Demo days" name="demo_days" type="number" form={form} setForm={setForm}/><Field label="Evaluation days" name="evaluation_days" type="number" form={form} setForm={setForm}/><Field label="Active checkpoint review days" name="active_checkpoint_review_days" type="number" form={form} setForm={setForm}/></div><Button tone="primary" disabled={busy} type="submit">Save retention</Button></form>}
  </div></aside></div>;
}

function Field({label,name,type="text",form,setForm}:{label:string;name:string;type?:string;form:Record<string,string>;setForm:(value:Record<string,string>)=>void}){return <label className="field"><span>{label}</span><input type={type} value={form[name]||""} onChange={event=>setForm({...form,[name]:event.target.value})}/></label>;}
function sectionReady(section:Section,checks:Record<string,boolean>){if(section==="models")return Boolean(checks.llm);if(section==="telegram")return Boolean(checks.control_bot&&checks.telethon);if(section==="security")return Boolean(checks.signing_key&&(checks.panel??true));return true;}
function sectionCopy(section:Section){return{models:"Routing and connectivity",telegram:"Control and data planes",security:"Signing and panel access",privacy:"Retention on this machine"}[section];}
function message(reason:unknown){return reason instanceof Error?reason.message:String(reason);}
