import { useEffect,useMemo,useRef,useState } from "react";
import { api } from "../api";
import { Button,Chip,EmptyState,ErrorState,LoadingState,PageHeading,Segmented,Surface,formatDate,titleCase } from "../components";
import { usePolling } from "../hooks";
import type { ActivityItem,JsonRecord } from "../types";
type Scope="important"|"all";
export function ActivityView({logs=false}:{logs?:boolean}){return logs?<Logs/>:<Ledger/>}
function Ledger(){const [scope,setScope]=useState<Scope>("important"),[severity,setSeverity]=useState("all"),[query,setQuery]=useState("");const path=`/api/activity?limit=300&scope=${scope}`;const rows=usePolling(()=>api<{items:ActivityItem[]}>(path).then(result=>result.items||[]),5000,[path]);const filtered=useMemo(()=>(rows.data||[]).filter(item=>(severity==="all"||String(item.severity||"info")==severity)&&JSON.stringify(item).toLowerCase().includes(query.toLowerCase())),[rows.data,severity,query]);if(rows.loading&&!rows.data)return <LoadingState label="Loading activity"/>;if(rows.error&&!rows.data)return <ErrorState message={rows.error} retry={()=>void rows.refresh()}/>;const groups=groupDays(filtered);return <div className="view"><PageHeading eyebrow="Audit trail" title="Activity ledger" copy="Important milestones by default; exhaustive audit events are one switch away." actions={<Button onClick={()=>exportRows(filtered)}>Export view</Button>}/><div className="observe-toolbar"><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search title, detail, category, or hash"/><Segmented value={scope} onChange={setScope} label="Ledger scope" items={[{value:"important",label:"Milestones"},{value:"all",label:"All"}]}/><select value={severity} onChange={event=>setSeverity(event.target.value)} aria-label="Severity"><option value="all">All severities</option><option value="error">Error</option><option value="warning">Warning</option><option value="success">Success</option><option value="info">Info</option></select></div><Surface className="ledger-surface">{filtered.length?<div className="ledger">{groups.map(group=><section key={group.label}><header><strong>{group.label}</strong><span>{group.items.length} of {filtered.length}</span></header>{group.items.map((item,index)=><article key={String(item.id||index)}><time>{formatClock(item.timestamp||item.ts)}</time><span className={`timeline-dot ${item.severity||"info"}`}/><small>{titleCase(item.category||"system")}</small><div><strong>{item.title||"Event"}</strong><p>{item.detail||"No additional detail recorded."}</p></div><code>{String(item.hash||item.chain_hash||"—").slice(0,14)}</code></article>)}</section>)}</div>:<EmptyState title="No activity matches this view" copy="Change the scope, severity, or search query."/>}</Surface></div>}
function Logs(){const [level,setLevel]=useState("all"),[query,setQuery]=useState(""),[follow,setFollow]=useState(true);const rows=usePolling(()=>api<{items:ActivityItem[]}>("/api/logs?limit=400").then(result=>result.items||[]),2000,[]);const body=useRef<HTMLDivElement>(null);const levels=useMemo(()=>["all",...new Set((rows.data||[]).map(item=>String(item.level||"info").toLowerCase()))],[rows.data]);const filtered=(rows.data||[]).filter(item=>(level==="all"||String(item.level||"info").toLowerCase()===level)&&JSON.stringify(item).toLowerCase().includes(query.toLowerCase()));useEffect(()=>{if(follow&&body.current)body.current.scrollTop=body.current.scrollHeight;},[filtered.length,follow]);if(rows.loading&&!rows.data)return <LoadingState label="Loading logs"/>;if(rows.error&&!rows.data)return <ErrorState message={rows.error} retry={()=>void rows.refresh()}/>;return <div className="view"><PageHeading eyebrow="Diagnostics" title="Diagnostic logs" copy="Runtime diagnostics with credentials redacted before display." actions={<Chip>Bounded 2,000-line buffer</Chip>}/><div className="observe-toolbar"><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search logger or message"/><div className="segmented">{levels.map(item=><button className={level===item?"active":""} key={item} onClick={()=>setLevel(item)}>{titleCase(item)} <span>{item==="all"?rows.data?.length:(rows.data||[]).filter(row=>String(row.level||"info").toLowerCase()===item).length}</span></button>)}</div><label className="follow-control"><input type="checkbox" checked={follow} onChange={event=>setFollow(event.target.checked)}/>Follow</label></div><Surface className="log-surface"><div className="log-viewer" ref={body}><header><span>Time</span><span>Level</span><span>Logger</span><span>Message</span></header>{filtered.map((row,index)=><article key={String(row.id||index)}><time>{formatClock(row.ts||row.timestamp)}</time><strong className={String(row.level||"info").toLowerCase()}>{String(row.level||"info").toUpperCase()}</strong><code>{String(row.logger||row.component||"hive")}</code><p>{String(row.message||row.detail||"")}</p></article>)}</div><footer className="log-footer"><span className="status-dot live"/>Streaming · credentials redacted before display <b>{filtered.length} visible</b></footer></Surface></div>}
function groupDays(items:ActivityItem[]){const groups=new Map<string,ActivityItem[]>();items.forEach(item=>{const ts=Number(item.timestamp||item.ts||0);const label=ts?formatDate(ts):"Undated";groups.set(label,[...(groups.get(label)||[]),item]);});return [...groups.entries()].map(([label,rows])=>({label,items:rows}));}
function formatClock(ts?:number){if(!ts)return"—";const value=ts<1e10?ts*1000:ts;return new Date(value).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit",second:"2-digit"});}
function exportRows(rows:ActivityItem[]){const blob=new Blob([JSON.stringify(rows,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`hive-ledger-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);}
