import { useMemo,useState } from "react";
import { api,post } from "../api";
import { Button,Chip,EmptyState,ErrorState,LoadingState,PageHeading,RiskBar,Segmented,Surface,formatDate,formatTime,titleCase,verdictTone } from "../components";
import { notify } from "../feedback";
import { usePolling } from "../hooks";
import type { CaseSummary,JsonRecord,PendingChat } from "../types";
interface CaseData{chats:PendingChat[];sessions:CaseSummary[];history:CaseSummary[]}
interface UnifiedRow extends JsonRecord{rowType:string;peer_id?:number;id?:string;history_id?:string;name?:string;last_message?:string;last_message_at?:number;last_message_ts?:number;ended_ts?:number;score?:number;verdict?:string;persona?:string;phase?:string;hvis?:number}
type Filter="all"|"live"|"queue"|"sealed";type Sort="risk"|"recent"|"oldest";
export function CasesView({navigate}:{navigate:(route:string)=>void}){
  const [search,setSearch]=useState(""),[filter,setFilter]=useState<Filter>("all"),[sort,setSort]=useState<Sort>("risk"),[persona,setPersona]=useState("confused_elderly"),[busyPeer,setBusyPeer]=useState<number|null>(null);
  const {data,error,loading,refresh}=usePolling(async()=>{const results=await Promise.allSettled([api<PendingChat[]>("/api/chats"),api<CaseSummary[]>("/api/sessions"),api<CaseSummary[]>("/api/history")]);return{chats:results[0].status==="fulfilled"?results[0].value:[],sessions:results[1].status==="fulfilled"?results[1].value:[],history:results[2].status==="fulfilled"?results[2].value:[]};},5000,[]);
  const rows=useMemo<UnifiedRow[]>(()=>{const query=search.trim().toLowerCase();const all:UnifiedRow[]=[...(filter==="all"||filter==="queue"?(data?.chats||[]).map(chat=>({...chat,rowType:"queue"} as UnifiedRow)):[]),...(filter==="all"||filter==="live"?(data?.sessions||[]).map(row=>({...row,rowType:"live"} as UnifiedRow)):[]),...(filter==="all"||filter==="sealed"?(data?.history||[]).map(row=>({...row,rowType:"sealed"} as UnifiedRow)):[])];return all.filter(row=>JSON.stringify(row).toLowerCase().includes(query)).sort((a,b)=>sort==="risk"?Number(b.score??-1)-Number(a.score??-1):sort==="oldest"?Number(a.last_message_at||a.last_message_ts||a.ended_ts||0)-Number(b.last_message_at||b.last_message_ts||b.ended_ts||0):Number(b.last_message_at||b.last_message_ts||b.ended_ts||0)-Number(a.last_message_at||a.last_message_ts||a.ended_ts||0));},[data,filter,search,sort]);
  async function takeOver(peerId:number){setBusyPeer(peerId);try{await post("/api/takeover",{peer_id:peerId,persona});notify({title:`Case ${peerId} started`,detail:`Persona: ${titleCase(persona)}.`,kind:"success"});await refresh();navigate(`case/live/${peerId}/conversation`);}catch(reason){notify({title:"Takeover could not start",detail:reason instanceof Error?reason.message:String(reason),kind:"error"});}finally{setBusyPeer(null);}}
  if(loading&&!data)return <LoadingState label="Loading cases"/>;if(error&&!data)return <ErrorState message={error} retry={()=>void refresh()}/>;
  const counts={all:(data?.chats.length||0)+(data?.sessions.length||0)+(data?.history.length||0),live:data?.sessions.length||0,queue:data?.chats.length||0,sealed:data?.history.length||0};
  return <div className="view cases-view"><PageHeading eyebrow="Operations" title="Cases" copy="Search and compare queued, live, and sealed cases without changing context."/><div className="case-toolbar"><label className="search-control"><span className="sr-only">Search cases</span><input type="search" value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search peer, account, verdict, or message"/></label><Segmented value={filter} onChange={setFilter} label="Case filter" items={[{value:"all",label:"All",count:counts.all},{value:"live",label:"Live",count:counts.live},{value:"queue",label:"Queue",count:counts.queue},{value:"sealed",label:"Sealed",count:counts.sealed}]}/><label><span>Sort</span><select value={sort} onChange={event=>setSort(event.target.value as Sort)}><option value="risk">Highest risk</option><option value="recent">Recent activity</option><option value="oldest">Oldest activity</option></select></label><label><span>Takeover persona</span><select value={persona} onChange={event=>setPersona(event.target.value)}><option value="confused_elderly">Confused elderly</option><option value="naive_young_adult">Naive young adult</option><option value="overseas_worker">Overseas worker</option><option value="small_business_owner">Small business owner</option></select></label></div><Surface className="cases-table-surface"><div className="cases-table"><header><span>Status</span><span>Case</span><span>Decision</span><span>Cumulative risk</span><span>Persona</span><span>Phase</span><span>HVIs</span><span>Activity</span><span/></header>{rows.map((row,index)=>{const kind=String(row.rowType);const peer=Number(row.peer_id);const id=String(row.id||row.history_id||peer);return <button key={`${kind}-${id}-${index}`} onClick={()=>kind==="queue"?void takeOver(peer):navigate(`case/${kind==="sealed"?"history":"live"}/${id}/conversation`)}><span><i className={`case-state ${kind==="live"?"active":kind==="sealed"?"sealed":"queue"}`}/><small>{titleCase(kind)}</small></span><span><strong>{row.name||`Peer ${peer}`}</strong><code>{peer||"—"}</code>{kind==="queue"&&<small>{String(row.last_message||"Pending private chat")}</small>}</span><Chip tone={verdictTone(String(row.verdict||""))}>{kind==="queue"?"Not assessed":titleCase(row.verdict)}</Chip><RiskBar value={typeof row.score==="number"?row.score:undefined}/><span>{kind==="queue"?titleCase(persona):titleCase(row.persona)}</span><code>{kind==="queue"?"PENDING":String(row.phase||"SEALED")}</code><span>{kind==="queue"?"—":Number(row.hvis||0)}</span><time>{formatDate(Number(row.last_message_at||row.last_message_ts||row.ended_ts),true)||formatTime(Number(row.last_message_at))}</time><b>{busyPeer===peer?"…":"›"}</b></button>})}</div>{!rows.length&&<EmptyState title="No cases match this view" copy="Change the filter or search terms. New takeover requests appear automatically."/>}</Surface></div>;
}
