import { useMemo, useState } from "react";
import { api, authenticatedUrl, post } from "../api";
import { compareCasesNewestFirst } from "../caseOrder";
import { Button, Chip, EmptyState, ErrorState, LoadingState, PageHeading, RiskBar, Segmented, Surface, SurfaceHeader, Timeline, titleCase, verdictTone } from "../components";
import { confirmAction, notify } from "../feedback";
import { useNow, usePolling } from "../hooks";
import type { ActivityItem, CaseSummary, Dashboard, PendingChat } from "../types";

type Filter="all"|"live"|"queue"|"sealed";
export function ConsoleView({navigate,openSetup}:{navigate:(route:string)=>void;openSetup:()=>void}){
  const now=useNow(),[filter,setFilter]=useState<Filter>("all"),[manualPeer,setManualPeer]=useState(""),[dismissingPeer,setDismissingPeer]=useState<number|null>(null);
  const {data,error,loading,refresh}=usePolling(()=>api<Dashboard>("/api/dashboard"),5000,[]);
  const history=usePolling(()=>api<CaseSummary[]>("/api/history").catch(()=>[]),10000,[]);
  const runtime=data?.runtime,metrics=data?.metrics;
  const attention=useMemo(()=>[...(data?.sessions||[])].sort((a,b)=>Number(b.score||0)-Number(a.score||0)).find(item=>Number(item.score||0)>=.85&&!item.analysis_pending),[data]);
  const oldestQueue=useMemo(()=>[...(data?.chats||[])].sort((a,b)=>Number(a.last_message_at||0)-Number(b.last_message_at||0))[0],[data]);
  const components=runtime?.components||{};const telethon=Object.entries(components).find(([key])=>/telethon|userbot|data/i.test(key));const degraded=Boolean(runtime?.running&&telethon&&!["up","ready","running","healthy","connected"].includes(String(telethon[1].state||"").toLowerCase()));
  const caseRows=(filter==="live"?(data?.sessions||[]):filter==="queue"?[]:filter==="sealed"?(history.data||[]):[...(data?.sessions||[]),...(history.data||[])]).slice().sort(compareCasesNewestFirst);
  async function runtimeAction(action:"start"|"restart"|"stop"){
    if(action==="stop"&&!await confirmAction({title:"Stop the HIVE runtime?",copy:"Telegram delivery and live analysis will pause.",confirmLabel:"Stop runtime",consequences:[{tone:"error",title:"Replies stop",detail:"Active personas stop sending messages until the runtime restarts."},{tone:"warning",title:"Stored evidence remains",detail:"The local panel and existing sealed bundles stay available."}]}))return;
    try{await post(`/api/runtime/${action}`);notify({title:`Runtime ${action} requested`,detail:"Readiness will update when the operation completes.",kind:"success"});await refresh();}catch(reason){notify({title:"Runtime action failed",detail:message(reason),kind:"error"});}
  }
  async function takeOver(chat:PendingChat){try{await post("/api/takeover",{peer_id:chat.peer_id,persona:"confused_elderly"});notify({title:`Case ${chat.peer_id} started`,detail:"The pending messages are entering the live analysis pipeline.",kind:"success"});navigate(`case/live/${chat.peer_id}/conversation`);}catch(reason){notify({title:"Takeover could not start",detail:message(reason),kind:"error"});}}
  async function dismiss(chat:PendingChat){if(!await confirmAction({title:`Dismiss request from peer ${chat.peer_id}?`,copy:"HIVE will remove this pending request without replying to the sender.",confirmLabel:"Dismiss request",consequences:[{tone:"info",title:"No message is sent",detail:"The sender is not notified that an operator dismissed the request."},{tone:"warning",title:"Pending messages are cleared",detail:"The current request leaves both the panel and Telegram approval queue."},{tone:"success",title:"Future contact can reopen it",detail:"A new inbound message can create a fresh takeover request."}]}))return;setDismissingPeer(chat.peer_id);try{await post(`/api/chats/${chat.peer_id}/dismiss`);notify({title:`Request ${chat.peer_id} dismissed`,detail:"No reply was sent. Future contact can create a new request.",kind:"success"});await refresh();}catch(reason){notify({title:"Request could not be dismissed",detail:message(reason),kind:"error"});}finally{setDismissingPeer(null);}}
  async function openManualPeer(){const peerId=Number(manualPeer);if(!Number.isSafeInteger(peerId)||peerId<=0){notify({title:"Enter a valid peer ID",detail:"Telegram peer IDs must be positive integers.",kind:"warning"});return;}try{await post("/api/takeover",{peer_id:peerId,persona:"confused_elderly"});notify({title:`Case ${peerId} opened`,detail:"Any pending messages are entering the live analysis pipeline.",kind:"success"});setManualPeer("");navigate(`case/live/${peerId}/conversation`);}catch(reason){notify({title:"Peer could not be opened",detail:message(reason),kind:"error"});}}
  async function seal(item:CaseSummary){if(!item.peer_id||!await confirmAction({eyebrow:"This cannot be undone",title:`Stop and seal peer ${item.peer_id}?`,copy:"HIVE will stop replying and publish only after rendering and signing succeed.",confirmLabel:"Seal anyway",consequences:[{tone:"error",title:"The persona stops replying",detail:"The stranger sees silence, not an automated goodbye."},{tone:"info",title:"The transcript becomes read-only",detail:"A signed PDF and portable ZIP are generated."},{tone:"success",title:"The pattern joins the case index",detail:"A privacy-reduced vector becomes available for candidate retrieval."}]}))return;try{const result=await post<Record<string,unknown>>(`/api/sessions/${item.peer_id}/stop`);notify({title:`Case ${item.peer_id} sealed`,detail:"The evidence bundle was rendered and signed.",kind:"success"});window.open(authenticatedUrl(String(result.download_url||"")),"_blank","noopener");await refresh();}catch(reason){notify({title:"Sealing failed; takeover remains active",detail:message(reason),kind:"error"});}}
  if(loading&&!data)return <LoadingState label="Loading operations console"/>;if(error&&!data)return <ErrorState message={error} retry={()=>void refresh()}/>;
  return <div className="view console-view"><PageHeading eyebrow={new Intl.DateTimeFormat(undefined,{weekday:"long",day:"numeric",month:"long"}).format(now)} title={runtime?.running&&!metrics?.active_sessions&&!metrics?.observed_chats?"Nothing needs you":runtime?.running?`${metrics?.active_sessions||0} takeovers running, ${metrics?.observed_chats||0} waiting`:"HIVE is ready when you are"} copy={runtime?.running?"Live cases, requests, and milestones update without moving your place.":"Review readiness, then start the approved research account."} actions={runtime?.running?<><Button onClick={()=>void runtimeAction("restart")}>Restart runtime</Button><Button tone="danger" onClick={()=>void runtimeAction("stop")}>Stop</Button></>:<><Button tone="primary" onClick={()=>void runtimeAction("start")}>Start agent</Button><Button onClick={openSetup}>Review setup</Button></>}/>
    {degraded&&<DegradedBanner detail={telethon?.[1].detail||"The Telegram data plane is unavailable."} peer={data?.sessions.find(row=>row.recovery_status==="paused_after_restart")?.peer_id} components={components} activity={data?.activity||[]} navigate={navigate}/>} {!runtime?.ready&&!degraded&&<div className="attention-banner warning"><span>!</span><div><strong>Setup needs attention</strong><p>{runtime?.error||"One or more required components are not ready."}</p></div><Button onClick={openSetup}>Open setup</Button></div>}
    {attention?<div className="attention-banner"><span>•</span><div><strong>Peer {attention.peer_id} crossed {(Number(attention.score)*100).toFixed(0)}%</strong><p>{attention.hvis||0} indicators · {attention.sandbox||0} sandbox runs · extraction settled, ready for review</p></div><div className="button-stack"><Button onClick={()=>navigate(`case/live/${attention.peer_id}/conversation`)}>Open case</Button><Button tone="primary" onClick={()=>void seal(attention)}>Seal now</Button></div></div>:oldestQueue?<div className="attention-banner"><span>•</span><div><strong>{oldestQueue.name||`Peer ${oldestQueue.peer_id}`} is waiting for review</strong><p>{oldestQueue.last_message||"A pending private chat requires an operator decision."}</p></div><Button tone="primary" onClick={()=>void takeOver(oldestQueue)}>Take over</Button></div>:runtime?.running&&<div className="calm-card"><span className="status-dot live"/><div><strong>Watching for the first eligible private chat</strong><p>Both planes are connected. Requests will appear here and in Telegram.</p></div><form onSubmit={event=>{event.preventDefault();if(manualPeer.trim())void openManualPeer();}}><input inputMode="numeric" value={manualPeer} onChange={event=>setManualPeer(event.target.value.replace(/\D/g,""))} placeholder="Enter peer ID"/><Button type="submit">Open peer</Button></form></div>}
    <div className="metric-row">{[["Active",metrics?.active_sessions],["Likely scams",metrics?.likely_scams],["Indicators",metrics?.hvis],["Sandbox runs",metrics?.sandbox_runs],["Agent turns",metrics?.turns]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value??"—"}</strong></div>)}</div>
    <div className="console-grid"><Surface className="case-overview"><SurfaceHeader title="Cases" action={<button className="text-button" onClick={()=>navigate("cases")}>Full list</button>}/><div className="filter-row compact"><Segmented value={filter} onChange={setFilter} label="Case filter" items={[{value:"all",label:"All",count:(data?.sessions.length||0)+(history.data?.length||0)},{value:"live",label:"Live",count:data?.sessions.length||0},{value:"queue",label:"Queue",count:data?.chats.length||0},{value:"sealed",label:"Sealed",count:history.data?.length||0}]}/></div>{filter==="queue"?(data?.chats.length?<div className="request-list">{data.chats.map(chat=><article key={chat.peer_id}><div><strong>{chat.name||`Peer ${chat.peer_id}`}</strong><p>{chat.last_message||"Media or empty message"}</p></div><div className="button-stack"><Button tone="primary" onClick={()=>void takeOver(chat)}>Take over</Button><Button disabled={dismissingPeer===chat.peer_id} onClick={()=>void dismiss(chat)}>{dismissingPeer===chat.peer_id?"Dismissing…":"Dismiss"}</Button></div></article>)}</div>:<EmptyState title="Queue clear" copy="Pending private chats will appear here and in Telegram."/>):caseRows.length?<div className="case-list">{caseRows.slice(0,8).map(item=><CaseRow key={item.id||item.history_id||item.peer_id} item={item} sealed={Boolean(item.id||item.history_id)} onOpen={()=>navigate(`case/${item.id||item.history_id?"history":"live"}/${item.id||item.history_id||item.peer_id}/conversation`)}/>)}</div>:<EmptyState title="No cases in this view" copy="Someone messages the approved account, HIVE creates one request, and approval starts a case." action={<div className="button-stack"><Button onClick={()=>navigate("demo")}>Run a demo scenario</Button><Button tone="quiet" onClick={openSetup}>Read the safeguards</Button></div>}/>}</Surface><div className="console-side"><Surface><SurfaceHeader title="Queue" copy={`${data?.chats.length||0} waiting`} action={<button className="text-button" onClick={()=>navigate("cases")}>Review all</button>}/>{data?.chats.length?<div className="queue-list">{data.chats.map(chat=><article key={chat.peer_id}><div><strong>{chat.name||chat.username||`Peer ${chat.peer_id}`}</strong><small>{relativeTime(chat.last_message_at)}</small><p>{chat.last_message||"Media or empty message"}</p></div><div className="button-stack"><Button tone="primary" onClick={()=>void takeOver(chat)}>Take over</Button><Button disabled={dismissingPeer===chat.peer_id} onClick={()=>void dismiss(chat)}>{dismissingPeer===chat.peer_id?"Dismissing…":"Dismiss"}</Button></div></article>)}</div>:<EmptyState title="Queue clear" copy="Pending private chats will appear here."/>}</Surface><Surface><SurfaceHeader title="Activity" action={<button className="text-button" onClick={()=>navigate("activity")}>Ledger</button>}/><Timeline items={data?.activity.slice(0,4)}/></Surface></div></div>
  </div>;
}
function CaseRow({item,sealed,onOpen}:{item:CaseSummary;sealed:boolean;onOpen:()=>void}){return <button className={`case-row ${item.recovery_status==="paused_after_restart"?"recovery":""}`} onClick={onOpen}><span className={`case-state ${sealed?"sealed":"active"}`}/><div><strong>{item.name||`Peer ${item.peer_id}`}</strong><small>{item.peer_id}</small></div><Chip tone={verdictTone(item.verdict)}>{titleCase(item.verdict||"not assessed")}</Chip><RiskBar compact value={item.score}/><span>{titleCase(item.persona)}</span><time>{relativeTime(item.last_message_ts||item.ended_ts)}</time><b>›</b></button>}
function DegradedBanner({detail,peer,components,activity,navigate}:{detail:string;peer?:number;components:Record<string,{state?:string;detail?:string}>;activity:ActivityItem[];navigate:(route:string)=>void}){const ordered=Object.entries(components).sort(([a],[b])=>componentPriority(a)-componentPriority(b)).slice(0,4);const events=activity.filter(item=>/disconnect|fail|pause|recover|restart|ready/i.test(`${item.title} ${item.detail}`)).slice(0,4);return <div className="degraded-state"><div className="degraded-banner"><span>!</span><div><strong>Replies are not being delivered</strong><p>{detail} Inbound messages remain journalled, so the evidence chain is preserved{peer?` while peer ${peer} remains recovery paused` : ""}.</p></div><div className="button-stack"><Button tone="primary" onClick={()=>window.location.reload()}>Reconnect data plane</Button><Button onClick={()=>navigate("logs")}>View logs</Button></div></div><div className="component-grid">{ordered.map(([name,item])=>{const healthy=/up|ready|running|healthy|connected/i.test(String(item.state));return <article key={name}><span className={`status-dot ${healthy?"success":"error"}`}/><div><strong>{titleCase(name)}</strong><p>{item.detail||`Component is ${item.state||"unknown"}.`}</p></div><Chip tone={healthy?"success":"danger"}>{titleCase(item.state||"unknown")}</Chip></article>})}</div><Surface className="break-sequence"><SurfaceHeader title="What broke" copy="Recent operational milestones around the interruption"/>{events.length?<Timeline items={events}/>:<EmptyState title="No failure sequence recorded" copy="Open Diagnostic logs for process-local detail while the permanent ledger continues recording."/>}{peer&&<div className="recovery-callout"><strong>Peer {peer} is recovery paused</strong><p>Open the case to Resume or Abandon its checkpoint.</p><Button onClick={()=>navigate(`case/live/${peer}/conversation`)}>Open recovery</Button></div>}</Surface></div>}
function componentPriority(name:string){return /userbot|telethon|data/i.test(name)?0:/control/i.test(name)?1:/sandbox/i.test(name)?2:/audit/i.test(name)?3:4}
function relativeTime(ts?:number){if(!ts)return"—";const ms=ts<1e10?ts*1000:ts;const minutes=Math.max(0,Math.round((Date.now()-ms)/60000));return minutes<1?"now":minutes<60?`${minutes}m ago`:minutes<1440?`${Math.round(minutes/60)}h ago`:`${Math.round(minutes/1440)}d ago`;}
function message(reason:unknown){return reason instanceof Error?reason.message:String(reason)}
